[package]
name = "smartcontracts"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.11.4"

[dev-dependencies]
assert_macros = "2.11.4"
cairo_test = "2.11.4"

[[target.starknet-contract]]
sierra = true

# [scripts]
# test = "snforge test"

# [tool.scarb]
# allow-prebuilt-plugins = ["snforge_std"]

# [[tool.snforge.fork]]
# name = "STARKNET_MAINNET"
# url = "https://starknet-mainnet.g.alchemy.com/v2/FIQ1qwifmra7ZqdkVHnZ2lHQAKG8j4Yd"
# block_id.tag = "latest"

# [[tool.snforge.fork]]
# name = "STARKNET_SEPOLIA"
# url = "https://starknet-sepolia.g.alchemy.com/v2/FIQ1qwifmra7ZqdkVHnZ2lHQAKG8j4Yd"
# block_id.tag = "latest"
