# Arcanum Protocol - Deployment Configuration

[sncast.default]
# Network configuration - using a different RPC for compatibility
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
account = "deployer"
wait-params = { timeout = 300, retry-interval = 10 }
block-explorer = "StarkScan"
show-explorer-links = true

# Account configuration
accounts-file = "/home/simze/.starknet_accounts/starknet_open_zeppelin_accounts.json"

[sncast.sepolia]
url = "https://starknet-sepolia.public.blastapi.io/rpc/v0_8"
account = "deployer"

[sncast.mainnet]
url = "https://starknet-mainnet.g.alchemy.com/v2/FIQ1qwifmra7ZqdkVHnZ2lHQAKG8j4Yd"
account = "deployer"